### ISSUE TITLE
Not working on latest vscode

### ISSUE THREAD

**Issue by ksmarty** [cjwit/section-word-count-targets#1]
Hi there,

As someone who writes almost all of their school assignments using markdown in vscode, your extension seemed like a silver bullet! Unfortunately, it doesn't seem to be working and I'm not sure why.

I installed it normally from the extensions marketplace, reloaded by window, appended '(Target: 300)' to a header, and yet it doesn't work. Do you have any ideas on how to fix this?

Thanks,
Kyle

**Comment by cjwit** [comment]
I'm sorry to hear this. I just tried it again on my system to be sure that it's still working after any VSCode upgrades, and it does seem to be alright. One possibility that drove me crazy with something else before: the window has to be large enough to show. Otherwise, I don't have any immediate suggestions. 

I put up a [selection word count extension](https://marketplace.visualstudio.com/items?itemName=witulski.selection-word-count), too. You may try that and, if it doesn't work, then it's something about how I set these up not wanting to collaborate with your system. (I don't have a way to test right now, so I may not be able to help much if that's the case.)

<img width="683" alt="Screen Shot 2021-03-03 at 10 40 17 AM" src="https://user-images.githubusercontent.com/16803017/109831265-4476fd80-7c0d-11eb-83b8-b69cfe1ab173.png">

**Comment by ksmarty** [comment]
Hi, I installed your other extension and it works perfectly. My screen is wide enough that everything is showing, so I doubt that's the problem. I'll give my computer a quick reboot and see if that fixes it. 

Thank you!

**Comment by ksmarty** [comment]
Nothing seems to be working unfortunately. Are there any settings I should change for markdown?

I also tested it on another computer running VSCodium and it doesn't work either.

**Comment by cjwit** [comment]
I wish I had something more for you, but I don't have the debugging capability for testing other systems. (I wrote the extension up for myself and am glad that it's worked for a few others.) I was wondering if it could be a problem recognizing that it's a markdown file, but that would prevent the other extension from working, too.

When I was setting this up the first time, I had a problem where it would work within the Extension Development Host window (F5), but not when installed as a regular extension. (See [here](https://code.visualstudio.com/api/get-started/your-first-extension) for more info.) You could try that to see if it makes a difference. I largely based this on the [word count demo](https://vscode-docs.readthedocs.io/en/stable/extensions/example-word-count/), and you may be able to do something similar to get exactly what you want, or to test for points where there is an issue.

**Comment by ksmarty** [comment]
No worries. Out of curiosity, what OS & version of vscode are you running? I would like to rule that out as a factor.

**Comment by cjwit** [comment]
No problem. I'm on macOS 10.14.6 with vsCode 1.54. Good luck!
